### ISSUE TITLE
Android implementation

### ISSUE THREAD

**Issue by Fullbaro** [dnandha/miauth#3]
In the last few weeks I tried to implement the IData interface using RxAndroidBle without much success. I got as far as connecting to the scooter, but the registration process fails with "auth: subscription timeout".
Is there an exact android implementation of the IData interface available somewhere?

**Comment by dnandha** [comment]
Hi @Fullbaro,
if you get an subscription timeout it could mean that a special combination has to be pressed on the device to allow pairing, e.g. pressing power button and then starting the registration process (again).
`DataRegister` and `DataLogin` are implementations of IData and both are available. You need to pass an `DataRegister` object to `AuthRegister` and it gets populated with the registration data (token / keys).
