### ISSUE TITLE
test_decrypt_uart test not implemented

### ISSUE THREAD

**Issue by nouun** [dnandha/miauth#9]
[`test_decrypt_uart`](https://github.com/dnandha/miauth/blob/main/lib/python/test/test_micrypto.py#L81-L85) has not been implemented in MiCrypto tests and is currently a copy of [`test_encrypt_uart`](https://github.com/dnandha/miauth/blob/main/lib/python/test/test_micrypto.py#L75-L79).

**Comment by dnandha** [comment]
Added via #f5b2cf1fbf3d191f55e860daf789c562d533dc37.

Thanks for raising the issue.
